name: CI 
on: [push]

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v3

   - name: Validate Kubernetes YAML
     run: kubectl apply -f deployment.yaml --dry-run=client

   - name: Lint DockerFile
     run: docker build --no-cache -t  test-image .  
